# Welcome to Jekyll!
#

# Site settings
title: "Antje & Mouhcine"
owner: Mouhcine El Amine # or company name
first_published: 2019 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://antjeandmouhcine.wedding" # the base hostname & protocol for your site

languages: ["en", "de", "it"]
exclude_from_localizations: ["fonts", "images", "css", "js", "CNAME"]
languageNames:
  en: English
  de: Deutsch
  it: Italiano



# Build settings
markdown: kramdown
#sass:
#  style: compressed

plugins:
  - jekyll-multiple-languages-plugin
